### ISSUE TITLE
no option to encrypt external drive

### ISSUE THREAD

**Issue by vicNric** [jas-per/luckyLUKS#10]
hi,
i've been exploring luckyLUKS over past while.. and have succesfully encrypted a file, which i copied to a 32gb usb drive, and have been using since. 

as you can see from the screenshot, there is **no option to select an external drive to encrypt a file to**... which is the reason i encrypted the usb drive by first creating the container on my desktop, and copying it over. 

![luckyLUKS no extDrive option](https://github.com/user-attachments/assets/f52cb465-6824-4385-a9c8-76e81c6b0bb6)

i hope i'm missing something. but i can't find a way to encrypt directly to an external drive... 

2nd query, related, is: **if i am able to encrypt directly to an external ssd/hdd, what is the max size of file i can create?**. as i'd love to fully encrypt my 1 and 1.5TG external drives... and i wonder if that's possible? (even using truecrypt via CLI). 

thanks for the great application. i've not dived in the CLI approach, as i'm not a linux tech wizard, so the GUI is very much appreciated.

**Comment by ghost** [comment]
I'm a bit late but if you go to your drive manager than there should be an encryption option.

**Comment by vicNric** [comment]
hi jas-per,
thanks for the response.. a tad late indeed.. but no worries. in the meantime i've learned how to use LUKS CLI, which is a 'better' approach imo, for me anyway.. to learn what i'm actually doing..
but good to know luckyLUKs could still be an option.. and possibly for others ill likely shared luks with in the future.
phil

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
