### ISSUE TITLE
Outdated info?

### ISSUE THREAD

**Issue by Brian6Mt** [jas-per/luckyLUKS#5]
I have just installed Linux Mate 18.04 LTS, encrypting the entire hard drive with Luks, I presume.. I have a thumb drive and an external 250 GB hard drive from that was encrypted by luks, but this OS wouldn't open them. The bubble said that there were no keys. The scant info I found about this OS stated that the only time Luks runs is during boot. The assumption is that there is no need to encrypt the home folder if the hard drive is already encrypted. There apparently was no thought about the possible need to decrypt an external storage drive which was encrypted by Luks. They do have Vera Crypt, but the transfer process to Vera Crypt with the external drive would be quite daunting and time consuming. 

[Update] It turns out that my thumb drive went bad. I dug out an old computer and that external drive from storage, and the thumb drive didn't work on the old one either, but the external hard drive works on both. This means that MY issue is fixed and that Ubuntu Mate 18.04 still has Luks, but the fact still remains that the directions on that website are outdated. The original post continues below:

 I found your site. Step 1 sort of worked, but not really, and step 2 didn't work at all: 
bman@bman-Oryx-Pro:~$ sudo add-apt-repository ppa:jas-per/lucky-luks
[sudo] password for bman: 
 luckyLUKS is a GUI for creating and (un-)locking encrypted volumes
from LUKS or Truecrypt container files

https://github.com/jas-per/luckyLUKS
 More info: https://launchpad.net/~jas-per/+archive/ubuntu/lucky-luks
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://APT.spideroak.com/ubuntu-spideroak-hardy release InRelease        
Ign:3 http://dl.google.com/linux/earth/deb stable InRelease                    
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease                     
Hit:6 http://us.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]    
Hit:8 http://dl.google.com/linux/earth/deb stable Release                      
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Hit:11 http://ppa.launchpad.net/costales/anoise/ubuntu bionic InRelease        
Hit:12 https://brave-browser-apt-release.s3.brave.com bionic InRelease         
Hit:13 https://repo.skype.com/deb stable InRelease                             
Ign:14 https://dl.bintray.com/resin-io/debian stable InRelease                 
Hit:15 https://s3-us-west-2.amazonaws.com/brave-apt artful InRelease           
Get:16 http://repository.spotify.com stable InRelease [3,302 B]                
Get:17 https://dl.bintray.com/resin-io/debian stable Release [1,878 B]         
Get:18 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:19 http://repo.vivaldi.com/stable/deb stable InRelease                     
Hit:20 http://repo.vivaldi.com/stable/deb stable Release                       
Get:21 https://dl.bintray.com/resin-io/debian stable Release.gpg [821 B]       
Hit:23 http://ppa.launchpad.net/flexiondotorg/telegram/ubuntu bionic InRelease 
Hit:24 https://wire-app.wire.com/linux/debian stable InRelease                 
Get:25 http://ppa.launchpad.net/jas-per/lucky-luks/ubuntu bionic InRelease [15.9 kB]
Err:16 http://repository.spotify.com stable InRelease            
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A87FF9DF48BF1C90
Hit:26 http://ppa.launchpad.net/openrazer/stable/ubuntu bionic InRelease       
Ign:21 https://dl.bintray.com/resin-io/debian stable Release.gpg               
Hit:28 http://ppa.launchpad.net/polychromatic/stable/ubuntu bionic InRelease   
Hit:29 http://ppa.launchpad.net/unit193/encryption/ubuntu bionic InRelease    
Hit:30 http://ppa.launchpad.net/webupd8team/indicator-kdeconnect/ubuntu bionic InRelease
Get:31 http://ppa.launchpad.net/jas-per/lucky-luks/ubuntu bionic/main i386 Packages [928 B]
Get:32 http://ppa.launchpad.net/jas-per/lucky-luks/ubuntu bionic/main amd64 Packages [928 B]
Get:33 http://ppa.launchpad.net/jas-per/lucky-luks/ubuntu bionic/main Translation-en [652 B]
Reading package lists... Done                       
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://dl.google.com/linux/earth/deb stable InRelease' doesn't support architecture 'i386'
W: GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A87FF9DF48BF1C90
E: The repository 'http://repository.spotify.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.bintray.com/resin-io/debian stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://dl.bintray.com/resin-io/debian stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
bman@bman-Oryx-Pro:~$ sudo chown root:root /usr/bin/luckyLUKS-1.2.0
chown: cannot access '/usr/bin/luckyLUKS-1.2.0': No such file or directory
bman@bman-Oryx-Pro:~$

**Comment by jas-per** [comment]
I think you mixed the installation instructions for using the ppa and manual installation - maybe I should rewrite that section to make things a bit clearer.. for the ppa installation just use these commands

> sudo add-apt-repository ppa:jas-per/lucky-luks
> sudo apt-get update && sudo apt-get upgrade
> sudo apt-get install python3-luckyluks-gtk

this gtk3-version should work best on your Mate-Desktop
