### ISSUE TITLE
Cannot change layout of the keyboard after mount container.

### ISSUE THREAD

**Issue by demonlibra** [jas-per/luckyLUKS#6]
Linux Mint 20
Russian localization

Cannot change layout of the keyboard after mount container.
Need to clear settings "Key(s) to change layout" and set it again
or run in terminal command
`setxkbmap -layout us,ru -option grp:alt_shift_toggle`

**Comment by jas-per** [comment]
not able to replicate this - there are 2 places where a subprocess gets started with language cleared (to be able to reliably parse the english output) but this is part of pythons subprocess module which really should be fine

closing for now, please provide more details if the problem still persists

**Comment by demonlibra** [comment]
Resolved after update to version 2.0.1.
Thank you.
