### ISSUE TITLE
Problems with README.rst docs

### ISSUE THREAD

**Issue by gpxlnx** [jas-per/luckyLUKS#7]
Dear upstream,
I am packaging luks for Debian and when packaging luckyluks, I get these warnings and errors:

P: luckyluks source: very-long-line-length-in-source-file README.rst line 91 is 1164 characters long (>512)

Could you fix these issues? To help, I will put a full explanation below.

Thanks a lot in advance.

Regards,

Guilherme Xavier

P: luckyluks source: very-long-line-length-in-source-file README.rst line 91 is 1164 characters long (>512)
N: 
N:   The source file includes a line length that is well beyond the normally
N:   human made code line length.
N:   
N:   This very long line length does not allow Lintian to do correctly some
N:   source file checks.
N:   
N:   This line could also be the result of some text injected by a computer
N:   program, and thus could lead to FTBFS bugs.
N:   
N:   Last but not least, long line in source code could be used to obfuscate
N:   the source code and to hide stuff like backdoors or security problems.
N:   
N:   It could be due to jslint source comments or other build tool comments.
N:   
N:   You may report this issue upstream.
N: 
N:   Visibility: pedantic
N:   Show-Always: no
N:   Check: cruft
N:   Renamed from: insane-line-length-in-source-file

**Comment by jas-per** [comment]
must be new in Lintian - splitting the line(s) with `\` should fix this without adding a real linebreak

**Comment by gpxlnx** [comment]
Jasper, as I'm a Debian packager I can't change the upstream source without using a Path, would it be possible for you to perform this line break in the source please? Once again, thanks for your attention.

**Comment by jas-per** [comment]
sure! will update the readme after testing and committing some updates (removing python2 and adding LUKS2 support) - probably by the end of the week

**Comment by jas-per** [comment]
fixed https://github.com/jas-per/luckyLUKS/commit/1c058e79ab3fdb9b6e3aea185a0e5b071fc1ffca
