### ISSUE TITLE
Abort executable before run

### ISSUE THREAD

**Issue by gpxlnx** [jas-per/luckyLUKS#8]
Dear upstream, when I run the luckyLUKS app I am getting the following error:
Do you know any solution for this error? 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/luckyLUKS/utils.py", line 181, in run
    response = json.loads(buf.strip(), encoding='utf-8')
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
Aborted

**Comment by jas-per** [comment]
encoding was there for running the same codebase on python2, this worked until python 3.8 I think

I'll push an updated version with all python2 quirks removed next week

**Comment by gpxlnx** [comment]
Thank you so much for your attention Jasper. If you can make this change it would be great. I'm waiting!!!

**Comment by gpxlnx** [comment]
Jasper, as a Debian packager I can't change the upstream source without using a Path, would it be possible for you to perform this line break in the source please? Once again, thanks for your attention.

**Comment by jas-per** [comment]
fixed https://github.com/jas-per/luckyLUKS/commit/f712306d6d51505b9cc3f5331a6be24a8a453681
