### ISSUE TITLE
Open an encrypted usb drive

### ISSUE THREAD

**Issue by Gajusbonus** [jas-per/luckyLUKS#9]
I have an usb drive thats encrypted with:
`sudo cryptsetup luksFormat --type luks1 /dev/sdb1`
`sudo cryptsetup luksOpen /dev/sdb1 backup2`
and finally:
`mkfs.ext4 /dev/mapper/backup2`

How can I open this one with the luckyLUKS gui ?
What to put in "container file" and "device name" ?
if this is not possible, then how do I proceed to make a new encrypted usb drive?

**Comment by jas-per** [comment]
this way you're encrypting on a partition level (the whole partition on that usb drive) - for simplicity luckyLUKS only uses container files. if you want to give that approach a try just format the usb drive as usual and then create an encrypted container on that drive using the luckyLUKS gui
the size of the container is the space you'll have available for encrypted files, so be aware that with fat32 formatted drives you can only create containers <4Gb - use eg ext or ntfs as the filesystem while formatting the usb drive to be able to create bigger containers
